import { economicTypeOptionsForDirection, formatMoney, matchModeOptions, titleCase } from "./formatters";
import type { Dispatch, SetStateAction } from "react";
import type { ClassificationMatchMode, ClassificationReviewGroup, ClassificationRule, EconomicType } from "./types";

type Props = {
  loading: boolean; reviewGroups: ClassificationReviewGroup[]; rules: ClassificationRule[]; savingKey: string | null;
  ruleDrafts: Record<string, { description: string; matchMode: ClassificationMatchMode }>; visibleCount: number;
  setRuleDrafts: Dispatch<SetStateAction<Record<string, { description: string; matchMode: ClassificationMatchMode }>>>;
  loadMore: () => void; saveRule: (input: { sourceId: number; description: string; direction: ClassificationReviewGroup["direction"]; matchMode: ClassificationMatchMode; economicType: EconomicType }, key: string) => void; deleteRule: (rule: ClassificationRule) => void;
};

export function ClassificationPage({ loading, reviewGroups, rules, savingKey, ruleDrafts, visibleCount, setRuleDrafts, loadMore, saveRule, deleteRule }: Props) {
  const remainingCount = reviewGroups.reduce((total, group) => total + group.transactionCount, 0);
  return <>
    <section className="mt-8"><div><p className="text-xs uppercase tracking-[0.24em] text-neutral-500">Classification review</p><h2 className="mt-2 text-xl font-semibold">Recurring descriptions without a rule</h2><p className="mt-2 text-sm text-neutral-400">{remainingCount} transaction{remainingCount === 1 ? "" : "s"} across {reviewGroups.length} description{reviewGroups.length === 1 ? "" : "s"} left to review.</p><p className="mt-1 text-sm text-neutral-500">Approving a type applies it to every matching transaction from this provider and to future imports.</p></div>
      {!loading && reviewGroups.length === 0 ? <div className="mt-5 rounded-2xl border border-dashed border-neutral-800 p-6 text-sm text-neutral-400">Every imported description has a rule.</div> : null}
      <div className="mt-5 space-y-3">{reviewGroups.slice(0, visibleCount).map(group => { const key = `${group.sourceId}:${group.direction}:${group.description}`; const draft = ruleDrafts[key] ?? { description: group.description, matchMode: "exact" as const }; return <article key={key} className="rounded-2xl border border-neutral-800 bg-neutral-900/60 p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><h3 className="font-medium text-neutral-100">{group.description}</h3><p className="mt-1 text-sm text-neutral-400">{group.sourceName} · {titleCase(group.direction)} · {group.transactionCount} transaction{group.transactionCount === 1 ? "" : "s"} · latest {group.latestTransactionDate}</p><p className="mt-2 text-sm text-neutral-500">{group.samples.map(sample => `${sample.transactionDate} ${formatMoney(sample.amountMinor, sample.currencyCode)}`).join(" · ")}</p></div><div className="flex max-w-lg flex-wrap gap-2"><input className="min-w-48 flex-1 rounded-lg border border-neutral-700 bg-neutral-900 px-3 py-1.5 text-sm text-neutral-100" value={draft.description} disabled={savingKey === key} onChange={event => setRuleDrafts(current => ({ ...current, [key]: { ...draft, description: event.target.value } }))} aria-label="Rule match text" /><select className="rounded-lg border border-neutral-700 bg-neutral-900 px-2 py-1.5 text-sm text-neutral-100" value={draft.matchMode} disabled={savingKey === key} onChange={event => setRuleDrafts(current => ({ ...current, [key]: { ...draft, matchMode: event.target.value as ClassificationMatchMode } }))} aria-label="Rule match mode">{matchModeOptions.map(matchMode => <option key={matchMode} value={matchMode}>{titleCase(matchMode)}</option>)}</select>{economicTypeOptionsForDirection(group.direction).map(economicType => <button key={economicType} className="rounded-lg border border-neutral-700 px-3 py-1.5 text-xs font-medium text-neutral-200 transition hover:border-neutral-500 hover:bg-neutral-800 disabled:cursor-not-allowed disabled:opacity-50" disabled={savingKey === key} onClick={() => saveRule({ sourceId: group.sourceId, description: draft.description, direction: group.direction, matchMode: draft.matchMode, economicType }, key)}>{savingKey === key ? "Saving…" : titleCase(economicType)}</button>)}</div></div></article>; })}</div>
      {reviewGroups.length > visibleCount ? <button className="mt-4 rounded-lg border border-neutral-700 px-4 py-2 text-sm text-neutral-200 hover:border-neutral-500 hover:bg-neutral-900" onClick={loadMore}>Load more classification groups</button> : null}
    </section>
    <section className="mt-8"><div><p className="text-xs uppercase tracking-[0.24em] text-neutral-500">Classification rules</p><h2 className="mt-2 text-xl font-semibold">Saved local decisions</h2></div>{!loading && rules.length === 0 ? <p className="mt-5 text-sm text-neutral-400">No rules approved yet.</p> : null}{rules.length > 0 ? <div className="mt-5 overflow-x-auto rounded-2xl border border-neutral-800"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-neutral-900 text-xs uppercase tracking-wide text-neutral-500"><tr><th className="px-4 py-3 font-medium">Provider</th><th className="px-4 py-3 font-medium">Match</th><th className="px-4 py-3 font-medium">Direction</th><th className="px-4 py-3 font-medium">Economic type</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y divide-neutral-800">{rules.map(rule => <tr key={rule.id} className="bg-neutral-950/30"><td className="px-4 py-3 text-neutral-400">{rule.sourceName}</td><td className="px-4 py-3 text-neutral-100">{titleCase(rule.matchMode)}: {rule.normalizedDescription}</td><td className="px-4 py-3 text-neutral-400">{titleCase(rule.direction)}</td><td className="px-4 py-3"><select className="rounded-lg border border-neutral-700 bg-neutral-900 px-2 py-1 text-sm text-neutral-100" value={rule.economicType} disabled={savingKey === `rule-${rule.id}`} onChange={event => saveRule({ sourceId: rule.sourceId, description: rule.normalizedDescription, direction: rule.direction, matchMode: rule.matchMode, economicType: event.target.value as EconomicType }, `rule-${rule.id}`)}>{economicTypeOptionsForDirection(rule.direction).map(economicType => <option key={economicType} value={economicType}>{titleCase(economicType)}</option>)}</select></td><td className="px-4 py-3 text-right"><button className="text-sm text-red-300 hover:text-red-200 disabled:opacity-50" disabled={savingKey === `delete-${rule.id}`} onClick={() => deleteRule(rule)}>{savingKey === `delete-${rule.id}` ? "Deleting…" : "Delete"}</button></td></tr>)}</tbody></table></div> : null}</section>
  </>;
}
