import { useState } from 'react';
import { Button } from '../components/ui/button';
import { formatMoney, titleCase } from "./formatters";
import type { PayPalPaymentLink } from "./types";

type Props = { loading: boolean; links: PayPalPaymentLink[]; savingKey: string | null; updateLink: (linkId: number, status: PayPalPaymentLink["status"]) => void };

export function ReconciliationPage({ loading, links, savingKey, updateLink }: Props) {
  const [status, setStatus] = useState<PayPalPaymentLink["status"]>("pending");
  const visibleLinks = links.filter(link => link.status === status);
  return <section className="mt-8"><div><p className="text-xs uppercase tracking-[0.24em] text-neutral-500">Reconciliation</p><h2 className="mt-2 text-xl font-semibold">PayPal payments funded by HSBC</h2><p className="mt-2 text-sm text-neutral-400">Confirm a match to keep the named PayPal purchase as the only expense in cash-flow totals.</p></div><div className="mt-5 flex flex-wrap gap-2">{(["pending", "confirmed", "rejected"] as const).map(value => <Button key={value} variant={status === value ? "secondary" : "ghost"} aria-pressed={status === value} onClick={() => setStatus(value)}>{value === "pending" ? "Needs review" : titleCase(value)} ({links.filter(link => link.status === value).length})</Button>)}</div>{!loading && visibleLinks.length === 0 ? <div className="mt-5 rounded-2xl border border-dashed border-neutral-800 p-6 text-sm text-neutral-400">No {status} matches.</div> : null}<div className="mt-5 space-y-3">{visibleLinks.map(link => { const key = `paypal-link-${link.id}`; const saving = savingKey === key; return <article key={link.id} className="rounded-2xl border border-neutral-800 bg-neutral-900/60 p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="text-xs uppercase tracking-[0.18em] text-neutral-500">{titleCase(link.status)} match</p><p className="mt-2 text-sm text-neutral-400">HSBC {link.hsbcTransaction.transactionDate} · {formatMoney(link.hsbcTransaction.amountMinor, link.hsbcTransaction.currencyCode)} · {link.hsbcTransaction.description}</p><p className="mt-1 text-sm text-neutral-100">PayPal {link.paypalTransaction.transactionDate.slice(0, 10)} · {formatMoney(link.paypalTransaction.amountMinor, link.paypalTransaction.currencyCode)} · {link.paypalTransaction.description}</p><p className="mt-2 text-xs text-neutral-500">{link.matchReason}</p></div><div className="flex flex-wrap gap-2">{link.status !== "confirmed" ? <button className="rounded-lg border border-emerald-700 px-3 py-1.5 text-sm text-emerald-200 hover:bg-emerald-950/50 disabled:opacity-50" disabled={saving} onClick={() => updateLink(link.id, "confirmed")}>{saving ? "Saving…" : "Confirm"}</button> : null}{link.status !== "rejected" ? <button className="rounded-lg border border-red-900 px-3 py-1.5 text-sm text-red-200 hover:bg-red-950/50 disabled:opacity-50" disabled={saving} onClick={() => updateLink(link.id, "rejected")}>Reject</button> : null}{link.status !== "pending" ? <button className="rounded-lg border border-neutral-700 px-3 py-1.5 text-sm text-neutral-200 hover:bg-neutral-800 disabled:opacity-50" disabled={saving} onClick={() => updateLink(link.id, "pending")}>Reopen</button> : null}</div></div></article>; })}</div></section>;
}
