import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { expect, test } from "bun:test";
import { migrate } from "drizzle-orm/bun-sqlite/migrator";
import { eq } from "drizzle-orm";
import { createDb } from "./client";
import { DrizzleRecurringPaymentRepository } from "./drizzle-recurring-payment-repository";
import { accounts, cashFlowExclusions, sources, transactions } from "./schema";
import { createRecurringRoutes } from "../http/recurring-routes";
import { recurringOverview } from "../../app/recurring-payments";

test("migration, persistence, exclusion changes, linking, and route validation", async () => {
  const db = createDb(join(mkdtempSync(join(tmpdir(), "recurring-test-")), "app.db"));
  migrate(db, { migrationsFolder: "drizzle" });
  const source = db.insert(sources).values({ slug: "test", name: "Test", kind: "bank" }).returning().get();
  const account = db.insert(accounts).values({ sourceId: source.id, name: "Current", kind: "bank_account", currencyCode: "GBP" }).returning().get();
  const rows = db.insert(transactions).values(["2026-01-01", "2026-02-01", "2026-03-01"].map(transactionDate => ({ sourceId: source.id, accountId: account.id, transactionDate, description: "STREAMING", amountMinor: -999, currencyCode: "GBP", transactionType: "purchase" as const, economicType: "expense" as const }))).returning().all();
  const repository = new DrizzleRecurringPaymentRepository(db);
  const routes = createRecurringRoutes(repository);
  const post = (body: unknown) => routes["/api/recurring-payments"].POST(new Request("http://localhost/api/recurring-payments", { method: "POST", body: JSON.stringify(body) }));
  const suggestion = recurringOverview(await repository.snapshot()).suggestions[0];
  expect(suggestion.frequency).toBe("monthly");
  expect((await post({ ...suggestion, anchorDate: "2026-02-30" })).status).toBe(400);
  expect((await post({ ...suggestion, amountMinor: -999 })).status).toBe(400);
  expect((await post({ ...suggestion, accountId: 999 })).status).toBe(400);
  const response = await post(suggestion);
  expect(response.status).toBe(200);
  const saved = await response.json();
  await repository.save({ ...saved, name: "Streaming service", status: "paused" }, saved.id);
  expect((await new DrizzleRecurringPaymentRepository(db).snapshot()).payments[0].name).toBe("Streaming service");
  expect(recurringOverview(await repository.snapshot()).suggestions).toHaveLength(0);
  db.insert(cashFlowExclusions).values({ transactionId: rows[1].id }).run();
  db.update(transactions).set({ economicType: "transfer" }).where(eq(transactions.id, rows[2].id)).run();
  expect(recurringOverview(await repository.snapshot()).payments[0].transactions).toHaveLength(1);
  await expect(repository.link(rows[1].id, saved.id)).rejects.toThrow("eligible expense");
  await repository.link(rows[0].id, saved.id);
  expect((await repository.snapshot()).links).toEqual([{ transactionId: rows[0].id, paymentId: saved.id }]);
  const newAccount = db.insert(accounts).values({ sourceId: source.id, name: "HSBC", kind: "bank_account", currencyCode: "GBP" }).returning().get();
  const method = { paymentId: saved.id, accountId: newAccount.id, description: "STREAMING HSBC", effectiveDate: "2026-04-01" };
  const change = (body: unknown) => routes["/api/recurring-payments/method"].POST(new Request("http://localhost/api/recurring-payments/method", { method: "POST", body: JSON.stringify(body) }));
  expect((await change({ ...method, effectiveDate: "2026-02-30" })).status).toBe(400);
  expect((await change({ ...method, accountId: 999 })).status).toBe(400);
  expect((await change(method)).status).toBe(200);
  db.insert(transactions).values({ sourceId: source.id, accountId: newAccount.id, transactionDate: "2026-04-01", description: "STREAMING HSBC", amountMinor: -999, currencyCode: "GBP", transactionType: "purchase", economicType: "expense" }).run();
  const reloaded = await new DrizzleRecurringPaymentRepository(db).snapshot();
  expect(reloaded.methods).toHaveLength(1);
  expect(recurringOverview(reloaded).payments[0].transactions).toHaveLength(2);
  expect(reloaded.payments[0].accountId).toBe(account.id);
  expect((await post({ ...saved, accountId: newAccount.id })).status).toBe(400);
  expect((await change({ ...method, description: "STREAMING corrected" })).status).toBe(200);
  expect((await repository.snapshot()).methods).toHaveLength(1);
  expect((await repository.snapshot()).methods[0].description).toBe("STREAMING CORRECTED");
  expect((await change({ ...method, previousEffectiveDate: method.effectiveDate, effectiveDate: "2026-03-31" })).status).toBe(200);
  expect((await repository.snapshot()).methods).toHaveLength(1);
  expect((await repository.snapshot()).methods[0].effectiveDate).toBe("2026-03-31");
  db.$client.close();
});
