import { format } from "date-fns";
import { CalendarIcon } from "lucide-react";
import { DayPicker } from "react-day-picker";
import { Popover, PopoverContent, PopoverTrigger } from "./popover";

type Props = { value: string; onChange: (value: string) => void; placeholder?: string };
export function DatePicker({ value, onChange, placeholder = "Select date" }: Props) {
  const selected = value ? new Date(`${value}T00:00:00`) : undefined;
  return <Popover><PopoverTrigger asChild><button className="mt-1 flex h-9 w-full items-center justify-between rounded-lg border border-neutral-700 bg-neutral-900 px-3 text-left text-sm text-neutral-100 transition hover:border-neutral-500"><span className={value ? "" : "text-neutral-500"}>{selected ? format(selected, "dd/MM/yyyy") : placeholder}</span><CalendarIcon className="size-4 text-neutral-400" /></button></PopoverTrigger><PopoverContent className="w-auto border-neutral-700 bg-neutral-900 p-3"><DayPicker mode="single" selected={selected} onSelect={date => { if (date) onChange(format(date, "yyyy-MM-dd")); }} styles={{ root: { color: "#e5e5e5" }, month: { position: "relative" }, month_caption: { height: "2.5rem", display: "flex", alignItems: "center", justifyContent: "center" }, nav: { position: "absolute", top: "0.25rem", left: 0, right: 0, display: "flex", justifyContent: "space-between", pointerEvents: "none" }, button_previous: { pointerEvents: "auto", color: "#d4d4d4", padding: "0.25rem" }, button_next: { pointerEvents: "auto", color: "#d4d4d4", padding: "0.25rem" }, chevron: { fill: "#d4d4d4" } }} classNames={{ root: "text-sm", months: "flex", month: "space-y-3", caption_label: "text-sm font-medium text-neutral-100", month_grid: "w-full border-collapse", weekdays: "text-neutral-500", weekday: "w-9 py-1 text-center text-xs", day: "h-9 w-9 text-center", day_button: "size-8 rounded text-neutral-200 hover:bg-neutral-800", selected: "[&>button]:bg-emerald-400 [&>button]:text-neutral-950 [&>button]:hover:bg-emerald-300", today: "[&>button]:border [&>button]:border-neutral-500", outside: "text-neutral-700", disabled: "opacity-40" }} /></PopoverContent></Popover>;
}
