import { useState } from 'react';
import { Button } from './button';
import { format } from "date-fns";
import { CalendarIcon } from "lucide-react";
import { DayPicker } from "react-day-picker";
import { Popover, PopoverContent, PopoverTrigger } from "./popover";

type Props = { value: string; onChange: (value: string) => void; placeholder?: string };
export function DatePicker({ value, onChange, placeholder = "Select date" }: Props) {
  const [open, setOpen] = useState(false);
  const selected = value ? new Date(`${value}T00:00:00`) : undefined;
  return <Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><Button type="button" variant="outline" className="mt-1 flex h-9 w-full items-center justify-between rounded-lg border border-neutral-700 bg-neutral-900 px-3 text-left text-sm text-neutral-100 transition hover:border-neutral-500"><span className={value ? "" : "text-neutral-500"}>{selected ? format(selected, "dd/MM/yyyy") : placeholder}</span><CalendarIcon className="size-4 text-neutral-400" /></Button></PopoverTrigger><PopoverContent className="w-auto border-neutral-700 bg-neutral-900 p-3"><DayPicker mode="single" selected={selected} onSelect={date => { onChange(date ? format(date, "yyyy-MM-dd") : ""); setOpen(false); }} footer={value ? <button type="button" className="mt-2 w-full rounded border border-neutral-700 px-3 py-1.5 text-sm text-neutral-300 transition hover:border-neutral-500 hover:bg-neutral-800 hover:text-neutral-100" onClick={() => { onChange(""); setOpen(false); }}>Clear</button> : undefined} styles={{ root: { color: "#e5e5e5" }, month: { position: "relative" }, month_caption: { height: "2.5rem", display: "flex", alignItems: "center", justifyContent: "center" }, nav: { position: "absolute", top: "0.25rem", left: 0, right: 0, display: "flex", justifyContent: "space-between", pointerEvents: "none" }, button_previous: { pointerEvents: "auto" }, button_next: { pointerEvents: "auto" } }} classNames={{ root: "text-sm", months: "flex", month: "space-y-3", caption_label: "text-sm font-medium text-neutral-100", month_grid: "w-full border-collapse", weekdays: "text-neutral-500", weekday: "w-9 py-1 text-center text-xs", day: "h-9 w-9 text-center", day_button: "size-8 rounded text-neutral-200 hover:bg-neutral-800", selected: "[&>button]:bg-emerald-400 [&>button]:text-neutral-950 [&>button]:hover:bg-emerald-300", today: "[&>button]:border [&>button]:border-neutral-500", outside: "text-neutral-700", disabled: "opacity-40", button_previous: "flex size-8 items-center justify-center rounded text-neutral-300 hover:bg-neutral-800", button_next: "flex size-8 items-center justify-center rounded text-neutral-300 hover:bg-neutral-800", chevron: "pointer-events-none size-6 fill-current", footer: "mt-1" }} /></PopoverContent></Popover>;
}
